### ISSUE TITLE
Custom HTTP status code

### ISSUE THREAD

**Issue by lukasz-lysik** [opentable/oc#234]
It would be nice to have a way to set custom status code for a component. E.g. if the component doesn't have a body for some reason, the header could be 204 No Content. Probably there are some other use cases like setting 30X code to redirect to different component (alongside with a header with the address of the new component).

**Comment by matteofigus** [comment]
Unfortunately the 204 no content assumes blank response, and for the clients we still need metadata as response to handle cache resolution, version negotiation, etc. So in short, this turns out to be quite trivial and I think there is lack of interest. So, I am closing this, but definitely up for reopening in case anyone would want to work on a PR again.
