### ISSUE TITLE
shrinkwrap errors

### ISSUE THREAD

**Issue by JonSchapiro** [opentable/oc#267]
Hi @matteofigus 

I seem to be getting an error when I try to shrinkwrap my project, which includes the oc-client.  It seems to  be failing as a result of the oc-client shrinkwrapping an invalid version of uglify-js.  Specifically, see

```javascript
  "uglify-js": {
      "version": "2.6.4",
      "from": "uglify-js@latest",
      "resolved": "https://registry.npmjs.org/uglify-js/-/uglify-js-2.6.4.tgz",
...
```

As you can see it requires the latest uglify-js, but resolves to 2.6.4, which is no longer the latest version.  We are still debugging, so we can't be certain this is our issue, but it seems likely.

cc: @maxgurewitz

**Comment by matteofigus** [comment]
Hi @JonSchapiro thanks for reporting the issue. I think that the easiest here is probably to lock the shrinkwrap to specific versions (2.6.4 instead of latest) - I'll prioritise a fix asap.

Consider, also, that shrinkwrapping the module itself is not something I am in love with (I prefer modules to have weak deps versioning and the main application, in case, to be in charge of shrinkwrapping) - but this is just a very short term measure for forcing some insecure dependencies to be upgraded while we wait to migrate some others (uglify is one of them indeed).

Matteo

**Comment by matteofigus** [comment]
@JonSchapiro we published a new version of the client with more strict versions. Would be good if you could try to upgrade and see if you can still reproduce.

In any case, I would recommend to remove the node_modules first in order go guarantee a deterministic dependency tree (especially if using npm@3).

Thanks
