### ISSUE TITLE
graceful-fs@2 and @3 support will be removed soon

### ISSUE THREAD

**Issue by ChALkeR** [opentable/oc#277]
Hi. `oc` is currently `#43` in my [list of modules](https://gist.github.com/ChALkeR/d39b49642e02277d2292d66c2ea0bced) that would likely to be broken when https://github.com/nodejs/node/pull/6413 lands (which is anticipated to happen before v7.0).

Note that `graceful-fs@1` and `graceful-fs@4` are ok and would not be broken by this, but a `require()` on `graceful-fs@2` or `graceful-fs@3` would cause an error soon.

That is, runtime warning `fs: re-evaluating native module sources is not supported.` would be turned into a throw.

If you or your deps use `graceful-fs@2` or `graceful-fs@3` in runtime — you are affected. 

Tracking: https://github.com/nodejs/node/issues/5213.

Note: `oc` just recently appeared (or re-appeared) in that list. Perhaps your dependencies changed in the last few days?

**Comment by matteofigus** [comment]
Hi @ChALkeR thanks for submitting the issue. I made a quick investigation and this seems to be related to [this change](https://github.com/opentable/oc/pull/274/files#diff-36018a6a9e1de1798516799b84841318L3053) related to revert a dependency upgrade (`tar.gz` module) that was causing some troubles. Version of subdependency `graceful-fs` changed from 4.1.4 to 3.0.8.

I think the plan is to migrate `tar-gz` to a more maintained module anyway. I'll keep this issue opened while we complete that, and will try to prioritise that to happen sooner rather than later 👍
