### ISSUE TITLE
Open Components as standalone services?

### ISSUE THREAD

**Issue by srcnix** [opentable/oc#330]
I was wondering if it's possible to use OC without a central repository/registry?

As an example, the following would be separate services:
- Header
- Footer
- Sidebar
- Activity

Another service, which exists to serve content would utilise each of these services. For example:
- Users

The User's service itself would be an OC.

The components: header, footer and sidebar; would be rendered server side. Whereas Acitvity would be rendered client side to allow faster resoponse times.

Would each then be versionable?

**Comment by matteofigus** [comment]
Hi @srcnix, thanks for the issue.
It may be possible, still not sure how much it makes sense.

* At the moment each registry is designed and prepared to host many components (in fact, we host more than 100 in ours)
* Each component has his own version (in fact, we have 2500 combinations of components/versions in ours)
* You can run multiple instances of the registry for scaling up horizontally
* Each component should be render-able server-side or client-side

Now, going to the idea of having a different api instance for each component name:
* At the moment a registry contains all the components that are published to it. If you really want, you can have 4 registry instances, each connected to a different s3 bucket (or same bucket but different subfolder). This way you would have 4 urls for your components. 
* The way a component nests a component server-side (via `context.renderComponent`) is designed to work in such way the components you want to nest are hosted in the same registry. This is optimal because there is not a subsequent http request for the nested components. But if you want to make a fifth registry for your "container" component and nest server-side via making a http request (for example using the `request` module) - you should already be able to do it. 

If I can ask, what drives you towards the decision/idea of having a single api for each component - instead of a single one for all of them?
