### ISSUE TITLE
ES2015 support in server.js

### ISSUE THREAD

**Issue by matthewdavidson** [opentable/oc#339]
Component authors are limited to writing `server.js` in es5 regardless of the node version the component registry is running on. I believe this is due to the usage of uglify (which [at present](https://github.com/mishoo/UglifyJS2/issues/448) supports only es5) in the component packaging process.

I see three options:

1. Introduce [babel](https://babeljs.io/docs/plugins/preset-es2015/) into the packaging process.
2. Drop uglify in favor of a minifier that supports es2015 (e.g. [babili](https://github.com/babel/babili) is the only one i know of 😒 )
3. Wait for uglify to [support es6](https://github.com/mishoo/UglifyJS2/issues/448)

Rationale: At best, it's awkward for component authors who write their client side code in es2015 to be limited to es5 in `server.js`. At worst it's confusing for newcomers to the codebase to see different javascript syntax across files.

Thoughts?

**Comment by matteofigus** [comment]
Agree, this has been on my list like forever. I was waiting for uglify to catchup and resisting to add babel because it would make the cli to grow quite a lot - but perhaps it's now time to reconsider.

I didn't know babili but looking at the code it looks to me that it is anyways a combination of babel + uglify, so I think my preference would for short term doing 1. with `es2015` preset (as a pre-minification process) and then 3. long term when uglify will be ready.

**Comment by matteofigus** [comment]
Done with #346
