### ISSUE TITLE
OC-Registry: Preview Panel outputs JSON instead of a HTML preview.

### ISSUE THREAD

**Issue by chriscartlidge** [opentable/oc#369]
- Since the new OC-Registry update the preview panel is not working anymore.

**Comment by matteofigus** [comment]
The issue is not related to the latest update.

When you open a preview page, the preview url is set to baseUrl. If you have 2 instances (private/public) and you navigate the private (while the public has `discovery:false`) you won't be able to see the preview in html format.

I think @mattiaerre mentioned that to me a while ago and I forgot to add an issue.

I think the solution is to set the preview url to the current host instead of using the baseurl to construct it.
