### ISSUE TITLE
support pre-release versions for components

### ISSUE THREAD

**Issue by BhautikDoshi** [opentable/oc#391]
@matteofigus 

We are using oc for packaging UI component which goes with corresponding microservice (docker). 
We are keeping version number consistent with npm package and docker and we need to have major.minor.patch.buildnumber format for legacy reasons. 
So for npm the best that would work is major.minor.patch-buildnumber - the pre-release format.  Seems like npm works fine and gives the correct latest on 'npm install <npm-package>' but for OC, there is an issue where 
it doesn't return a latest version and issue seems to be with semver.maxSatisfying not dealing with pre-release versions.
https://github.com/npm/node-semver/issues/156
So I found semver-extra which handles prelease versions in finding the latest one among those.
https://github.com/kaelzhang/node-semver-extra

I tried updating oc/src/registry/domain/version-handler.js to use semver-extra when no version specified:

From:
```
    return semver.maxSatisfying(availableVersions, requestedVersion) || undefined;
```
To:
```    
    if (requestedVersion !== '') {
      return semver.maxSatisfying(availableVersions, requestedVersion) || undefined;
    }
    return semverExtra.max(availableVersions);
```
This seems to work for us and it does find latest pre-release version. Let me know if there is any other alternative approach.

And if you agree with this code change and would like to support prelease versions, I can submit a PR.

**Comment by BhautikDoshi** [comment]
Example:
component 'an-barracuda' has version numbers as 1.0.1-12, 1.0.1-14, 1.0.1-15
semver.maxSatisfying returns null so UI doesn't  even work. 

GET http://localhost:3030/an-barracuda/~info returns:
```
{
"err": "Component \"an-barracuda\" with version \"{1}\" not found on local repository"
}
```
With specific version works: GET http://localhost:3030/an-barracuda/1.0.1-12/~info

Doesn't work:
```
<oc-component href="/oc/an-barracuda"></oc-component> 
```

Works:
```
<oc-component href="/oc/an-barracuda/1.0.1-12"></oc-component>
```

**Comment by matteofigus** [comment]
I have mixed feelings here.

1) I agree that when only pre-release versions are available, latest should return the latest for a pre-release instead of a 404
2) I disagree that when both stable and more recent pre-relese are present, the pre-release should be provided when asking latest. I think this would go against node's default behaviour, and that may break people's code and expectations.

What if we instead do something like:
```js
var version = semver.maxSatisfying(availableVersions, requestedVersion) || undefined;
var max = semverExtra.max(availableVersions);
var isLatest = requestedVersion === '';
return version || (isLatest && max) || undefined;
```
In this way: 
* [1.0.0, 2.0.0-pre] => latest would match `1.0.0`
* [0.1.1-pre] => latest would match `0.1.1-pre`
* [0.0.1, 0.3.0-pre, 1.0.0] => 0.x.x would match `0.0.1`
* [0.1.1-pre, 0.3.0-pre, 1.0.0] => 0.x.x would 404

It sounds to me that this would be exactly what you get currently with npm.

Other people's opinion here? @mattiaerre @federicomaffei @nickbalestra @jwhayes

**Comment by jwhayes** [comment]
@matteofigus I like your proposal. That way we get best of both worlds.

**Comment by federicomaffei** [comment]
@matteofigus +1

**Comment by mattiaerre** [comment]
I put together this gist some time ago:

https://gist.github.com/mattiaerre/6bd5124a7d5aac4e2cae00642ba6bbd9

it looks like more or less what you are proposing 😉

**Comment by BhautikDoshi** [comment]
@matteofigus, 
Like your proposal. Will work for our use case and agree about mix of pre-release, release should always give released one for latest.

let me know if you will fix it or want me to send you PR based on your proposal?
Would like to get this in ASAP to avoid local patching. Thanks.

**Comment by matteofigus** [comment]
@BhautikDoshi that's great.

If you would be able to make a PR, it would be fantastic!
