### ISSUE TITLE
var => let/const

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#436]
A non critical optimisation that would be ideal for a first time contribution to OC.

Being very careful and perhaps splitting the work into multiple PRs to improve safety :rofl:

**Comment by elboletaire** [comment]
Eslint may help with that:

- http://eslint.org/docs/rules/no-var
- http://eslint.org/docs/rules/prefer-const

**Comment by matteofigus** [comment]
Yeah, actually @elboletaire you remind me that as part of this, we should probably move from jshint to eslint as it's much better for that!

**Comment by nickbalestra** [comment]
=> https://github.com/prettier/prettier

**Comment by elboletaire** [comment]
@matteofigus moving to eslint would be a good move, since jshint seems a bit outdated for all the ES6 stuff. Adding eslint to the project is as easy as `eslint --init`, and specify the source folders after asking some questions.

In fact I've done it locally but, there's something that scares me a bit... all that double negations found in [a][1] [lot][2] [of][3] [files][4]. Are they really needed? If they're there for casting to bools, wouldn't it be better to use ES5's `ToBoolean`?

Obviously I can ignore the warnings just changing a rule, although I'm still curious about it.

PS. If you want I can do a PR with the eslint added respecting the current "rules", and then another to change all the `var` with `const` and `let`.

[1]: https://github.com/opentable/oc/blob/master/src/cli/domain/watch.js#L12
[2]: https://github.com/opentable/oc/blob/f9f2dbb42329130237f2cceba554221836eb5751/src/cli/domain/get-missing-deps.js#L21
[3]: https://github.com/opentable/oc/blob/f9f2dbb42329130237f2cceba554221836eb5751/src/cli/domain/npm-installer.js#L8
[4]: https://github.com/opentable/oc/blob/master/src/cli/facade/dev.js#L25

**Comment by matteofigus** [comment]
@elboletaire the !!castings definitely need to be checked one by one, it may be an hard work. I think most of them are not necessary.

I would love a PR for eslint, but I would first like to ensure everybody wants it. @nickbalestra you linked prettier which seems a nice project but I don't know so much about it. Do you think switching to eslint is something we still want to do it independently from prettier, or are the two things mutually exclusive?

**Comment by mattiaerre** [comment]
@matteofigus I am not a prettier expert either but I think that if we incrementally improve our coding style, an eslint first step will not stop us to move towards prettier later if we want to. I, on the other hand, use eslint a lot and I see all the benefits.

// cc @elboletaire @nickbalestra

**Comment by nickbalestra** [comment]
Yes, you can use both in combinations (hey complete each other an solve slightly different problems.). I would suggest a two fold process as well:

1. switch to eslint
2. add prettier to [eslint](https://github.com/not-an-aardvark/eslint-plugin-prettier).

Would ❤️   to see @elboletaire PR for eslint :)And love how he suggest to takle it into sub PRs (eslint first, then let, const, ..)

**Comment by matteofigus** [comment]
Nice! So yeah if you want to make a PR go on, thanks @elboletaire !!

**Comment by elboletaire** [comment]
Sure, I'll try to do it during this week 😃

**Comment by nickbalestra** [comment]
@elboletaire @matteofigus @mattiaerre If is not too urgent, I would like to investigate a bit more into prettier, before going esling...

**Comment by elboletaire** [comment]
Use the autodetect feature, try to fix any warnings adapting the rules to your current code style (if can't adapt them, just disable). That for the eslint file creation (first PR).

After that, change the rules that we want to switch to, like the `cost`/`let`, and fix the issues (many of them can be automatically fixed with `--fix`).

**Comment by nickbalestra** [comment]
Great, my concern was not to start with too many rules or presets already, but I like your plan @elboletaire !
