### ISSUE TITLE
Plugins detective is broken

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#445]
I believe the plugin detective used to parse the minified ES5 server.js to try to catch how `context` was transformed, and then would seek for `(that).plugins.(something)` calls in order to detect calls to not supported plugins. Now that we are bundling and compiling with Babili the Regex doesn't work anymore: https://github.com/opentable/oc/blob/master/src/registry/domain/plugins-detective.js#L7

Maybe we can discuss how to improve that. If we can't, we can rather remove the check and let the registry throw (which would then fire a domain error with a component's 5xx response).

**Comment by mattiaerre** [comment]
@matteofigus happy to have a look at this issue if you like

**Comment by matteofigus** [comment]
ok! thanks

**Comment by mattiaerre** [comment]
@matteofigus it looks like `detective` is only used here:

https://github.com/opentable/oc/blob/master/src/registry/routes/helpers/get-component.js#L341

inside the `handleError` function that is raised only if `domain.on('error', handleError)`:

https://github.com/opentable/oc/blob/master/src/registry/routes/helpers/get-component.js#L365

so the detective logic is only exercised if there is an error; if I do not register a plugin and I try to get a component that uses one, this `on error` is never raised because there is no error; I've got the feeling that the detective maybe still work but the `get-component` functionality doesn't behave as expected; or am I missing something?

**Comment by mattiaerre** [comment]
@matteofigus as #495 has been merged shall we close this issue?

**Comment by matteofigus** [comment]
Oh yeah. Thanks!
