### ISSUE TITLE
Rendering one component with oc-client doesn't support parameters as object

### ISSUE THREAD

**Issue by gtrias** [opentable/oc#485]
oc version: 0.37.3
oc-client version:  2.1.13

Requesting one component with parameters as object doesn't pass the parameters as expected.
```javascript
{
  "hello": "world",
  "memberships": {
    "selector": "#main-app",
    "apikey": "1234"
  }
}
```
Produces the next request:

```
GET /widget-name/?hello=world&memberships=
```
If you try to render the component with another one it works as expected because the request is made using POST method.

**Comment by matteofigus** [comment]
Hi @gtrias this is by design.

Component parameters can be of type string, number, or boolean, but not objects. We took this decision on the very beginning when designing OC, to enforce clean and simple APIs. 

Do you think you could flatten the structure ("membershipSelector" and "membershipApiKey")?

**Comment by gtrias** [comment]
Sure, I can flatten the structure.
For me it makes sense to group certain parameters in objects in order to allow better parameter organization in a widgets with a lot of them but it's ok.
Thanks. Closing the issue then..

**Comment by elboletaire** [comment]
I think that this should be reconsidered. I would understand what you've done if the client was something everyone needs to use the same way, but it's not the case. I can use the client as I want, and, if I decide to use objects, is my decision.

Moreover, I think it's an inconsistency to have it behaving differently when we request one or more than one widgets.

If the `POST` (more than one widget) currently supports the nested params, why don't support it with the `GET` (just one widget)?

**Comment by matteofigus** [comment]
@elboletaire I see. To be honest, I am not sure the POST working is wanted behaviour. In fact that is untested and the fact it works is coincidental.

I think that having the parameters expressed in a flatten structure is good because enforces simplicity and makes the contract easy to document, maintain, and share.

On the other hand, if other people inside the community disagrees, we can change it 👍
In that case, it would involve adding tests for both POST and GET, and make all the clients to work with that convention.

In this regard, I think I would like here an opinion from @mattiaerre @nickbalestra and all the other contributors? Perhaps we can link this issue in the gitter chat to be more inclusive.

**Comment by elboletaire** [comment]
> In that case, it would involve adding tests for both POST and GET, and make all the clients to work with that convention.

I think this is important, either if we choose to accept parameters as objects or not.

Waiting to hear opinions from Nick and Mattia.

**Comment by mattiaerre** [comment]
yes we should definitely have a unified API that tells us how to consume components; It'd be cool to start a new conversation and list all the methods we are accepting and the structures of the parameters and try to understand where the differences are. I do agree w/ you @elboletaire and @matteofigus, either way, we should aim for a consistent API.

**Comment by elboletaire** [comment]
Any news about this?
