### ISSUE TITLE
.babelrc file can interfere with oc babel on package and publish 

### ISSUE THREAD

**Issue by antwhite** [opentable/oc#611]
### Steps to reproduce
create .babelrc file
```
{
  "presets": [
    [
      "env",
      {
        "debug": true
      }
    ]
  ]
}
```

Run `oc dev .`

See debug output of babel
```
babel-preset-env: `DEBUG` option

Using targets:
{}

Modules transform: commonjs
```

I'm not sure how they could interact but it would be better if oc babel was isolated from global settings

**Comment by nickbalestra** [comment]
What will be the usecase of having `.babelrc` in your project while not wanting it to interface with the components themselves?

**Comment by antwhite** [comment]
You could be hosting a babelified microsite with components inside

**Comment by nickbalestra** [comment]
So it seems that a the dotfile has precedence over the configuration given to the babel-loader within webpack. A safe solution will be to move the babel related configuration within 

- https://github.com/opencomponents/base-templates/blob/master/packages/oc-webpack/lib/configurator/index.js#L29
- https://github.com/opencomponents/oc-template-react/blob/master/packages/oc-template-react-compiler/lib/to-abstract-base-template-utils/webpackConfigurator.js#L65

into its own scoped `.babelrc` file so that it will shadow other `.babelrc` file present elsewhere in the project/machine

**Comment by nickbalestra** [comment]
No overrides via a root `.babelrc` are now possible 
- oc version 0.42.1
  - oc-template-jade-compiler 6.1.8
  - oc-template-handlebars-compiler 6.1.8
- oc-template-react-compiler 1.0.7
